<html>
<head>
<title>TestNG:  GWB-Tests</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>GWB-Tests</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>26/7/0</td>
</tr><tr>
<td>Started on:</td><td>Thu Mar 07 20:15:17 IST 2024</td>
</tr>
<tr><td>Total time:</td><td>33 seconds (33129 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin()'><b>VerifyInvalidFnameBankManagerLogin</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:41)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace627746290", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace627746290'><pre>java.lang.AssertionError: First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin()'><b>VerifyInvalidLnameBankManagerLogin</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:46)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace231191650", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace231191650'><pre>java.lang.AssertionError: Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyPostLogoutFunctionality()'><b>VerifyPostLogoutFunctionality</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyPostLogoutFunctionality(CustomerLoginFunctionalitiesTest.java:112)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace880934808", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace880934808'><pre>java.lang.AssertionError: Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyPostLogoutFunctionality(CustomerLoginFunctionalitiesTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyredirectToNonaccessablePageFunctionality()'><b>VerifyredirectToNonaccessablePageFunctionality</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyredirectToNonaccessablePageFunctionality(CustomerLoginFunctionalitiesTest.java:117)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1920147706", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1920147706'><pre>java.lang.AssertionError: Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyredirectToNonaccessablePageFunctionality(CustomerLoginFunctionalitiesTest.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositInValidAmount()'><b>depositInValidAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositInValidAmount(CustomerLoginFunctionalitiesTest.java:52)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace967343730", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace967343730'><pre>java.lang.AssertionError: No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositInValidAmount(CustomerLoginFunctionalitiesTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionResetFunctionalities()'><b>transactionResetFunctionalities</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionResetFunctionalities(CustomerLoginFunctionalitiesTest.java:92)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2072076651", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2072076651'><pre>java.lang.AssertionError: No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionResetFunctionalities(CustomerLoginFunctionalitiesTest.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInValidAmount()'><b>withdrawInValidAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td><div><pre>java.lang.AssertionError: No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInValidAmount(CustomerLoginFunctionalitiesTest.java:73)
... Removed 30 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace551056181", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace551056181'><pre>java.lang.AssertionError: No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInValidAmount(CustomerLoginFunctionalitiesTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyBankManagerLogin()'><b>VerifyBankManagerLogin</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyBankManagerLoginBtnFunctionality()'><b>VerifyBankManagerLoginBtnFunctionality</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyCustomerLogin()'><b>VerifyCustomerLogin</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyDuplicateBankManagerLogin()'><b>VerifyDuplicateBankManagerLogin</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyEmptyFieldBankManagerLogin()'><b>VerifyEmptyFieldBankManagerLogin</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifyHomeBtn()'><b>VerifyHomeBtn</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifyHomeBtnFunctionality()'><b>VerifyHomeBtnFunctionality</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyLogoutFunctionality()'><b>VerifyLogoutFunctionality</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifyNonAccountCustomersFunctionality()'><b>VerifyNonAccountCustomersFunctionality</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>2</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyOpenAccountFunctionality()'><b>VerifyOpenAccountFunctionality</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifyTitle()'><b>VerifyTitle</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifybankManagerLoginBtn()'><b>VerifybankManagerLoginBtn</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifybankManagerLoginBtnFunctionality()'><b>VerifybankManagerLoginBtnFunctionality</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifycustLoginBtn()'><b>VerifycustLoginBtn</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.HomeDashBoardTest.VerifycustLoginBtnFunctionality()'><b>VerifycustLoginBtnFunctionality</b><br>Test class: com.crm.qa.testcases.HomeDashBoardTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.HomeDashBoardTest@5ef5c734</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifycustLoginBtnFunctionality()'><b>VerifycustLoginBtnFunctionality</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.deleteCustomerFunctionality()'><b>deleteCustomerFunctionality</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositDecimalAmount()'><b>depositDecimalAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositValidAmount()'><b>depositValidAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.searchCustomersFunctionalityByID()'><b>searchCustomersFunctionalityByID</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.searchCustomersFunctionalityByName()'><b>searchCustomersFunctionalityByName</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.searchCustomersFunctionalityByPostCode()'><b>searchCustomersFunctionalityByPostCode</b><br>Test class: com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest@d771cc9</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionBackFunctionalities()'><b>transactionBackFunctionalities</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawDecimalAmount()'><b>withdrawDecimalAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInsufficientAmount()'><b>withdrawInsufficientAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>0</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
<tr>
<td title='com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawValidAmount()'><b>withdrawValidAmount</b><br>Test class: com.crm.qa.testcases.CustomerLoginFunctionalitiesTest</td>
<td></td>
<td>1</td>
<td>com.crm.qa.testcases.CustomerLoginFunctionalitiesTest@36b4091c</td></tr>
</table><p>
</body>
</html>